import { Ipost } from "../../models/post";

export const postData: Array<Ipost> = [
  {
    userId: 11,
    id: 11,
    title: 'Understanding Angular Core Concepts',
    body: 'Angular is a powerful framework that helps developers build scalable and maintainable web applications efficiently.',
  },
  {
    userId: 12,
    id: 12,
    title: 'Getting Started With TypeScript',
    body: 'TypeScript adds static typing to JavaScript, making your code more reliable and easier to debug in large projects.',
  },
  {
    userId: 13,
    id: 13,
    title: 'CSS Flexbox Layout Guide',
    body: 'Flexbox is a modern CSS layout model that allows you to design flexible and responsive page structures easily.',
  },
  {
    userId: 14,
    id: 14,
    title: 'Node JS For Beginners',
    body: 'Node.js is a runtime environment that lets you run JavaScript on the server side for building backend applications.',
  },
  {
    userId: 15,
    id: 15,
    title: 'Introduction To REST APIs',
    body: 'REST APIs allow different applications to communicate over HTTP using standard methods like GET, POST, PUT and DELETE.',
  },
  {
    userId: 16,
    id: 16,
    title: 'MongoDB Database Basics Explained',
    body: 'MongoDB is a NoSQL database that stores data in flexible JSON-like documents instead of traditional relational tables.',
  },
  {
    userId: 17,
    id: 17,
    title: 'How JavaScript Promises Work',
    body: 'Promises in JavaScript handle asynchronous operations by representing a value that will be available in the future.',
  },
  {
    userId: 18,
    id: 18,
    title: 'Angular Services And Dependency Injection',
    body: 'Services in Angular are reusable classes that handle business logic and can be injected into any component easily.',
  },
  {
    userId: 19,
    id: 19,
    title: 'Bootstrap Grid System Tutorial',
    body: 'The Bootstrap grid system uses a series of containers, rows and columns to layout content across different screen sizes.',
  },
  {
    userId: 20,
    id: 20,
    title: 'Understanding Async Await Syntax',
    body: 'Async await is modern JavaScript syntax that makes asynchronous code look and behave more like synchronous code.',
  },
  {
    userId: 21,
    id: 21,
    title: 'React Vs Angular Comparison',
    body: 'React is a UI library while Angular is a full framework, each having different strengths depending on your project needs.',
  },
  {
    userId: 22,
    id: 22,
    title: 'HTTP Client In Angular',
    body: 'Angular HttpClient module allows you to make HTTP requests to backend APIs and handle responses using RxJS observables.',
  },
  {
    userId: 23,
    id: 23,
    title: 'JavaScript Array Methods Explained',
    body: 'Array methods like map, filter and reduce are powerful tools that help you transform and manipulate data in JavaScript.',
  },
  {
    userId: 24,
    id: 24,
    title: 'Building Reusable Angular Components',
    body: 'Reusable components in Angular reduce code duplication and help maintain consistency across the entire application interface.',
  },
  {
    userId: 25,
    id: 25,
    title: 'Express JS Server Setup Guide',
    body: 'Express.js is a minimal Node.js framework that makes it easy to build fast and scalable backend web server applications.',
  },
  {
    userId: 26,
    id: 26,
    title: 'CSS Grid Layout For Beginners',
    body: 'CSS Grid is a two-dimensional layout system that gives you full control over rows and columns in web page design.',
  },
  {
    userId: 27,
    id: 27,
    title: 'RxJS Observables In Angular',
    body: 'RxJS observables are used in Angular to handle streams of asynchronous data like HTTP responses and user input events.',
  },
  {
    userId: 28,
    id: 28,
    title: 'Git Version Control For Developers',
    body: 'Git is a distributed version control system that helps developers track code changes and collaborate on projects effectively.',
  },
  {
    userId: 29,
    id: 29,
    title: 'Angular Routing And Navigation',
    body: 'Angular Router enables navigation between different views and components using URL paths in a single page application.',
  },
  {
    userId: 30,
    id: 30,
    title: 'JavaScript Event Loop Explained',
    body: 'The JavaScript event loop handles asynchronous callbacks by managing the call stack and task queue in the browser runtime.',
  },
  {
    userId: 31,
    id: 31,
    title: 'Angular Forms Reactive Approach',
    body: 'Reactive forms in Angular provide a model-driven approach to handling form inputs with more control and flexibility.',
  },
  {
    userId: 32,
    id: 32,
    title: 'What Is Two Way Binding',
    body: 'Two way data binding in Angular keeps the component class and template in sync using the ngModel directive automatically.',
  },
  {
    userId: 33,
    id: 33,
    title: 'MEAN Stack Overview Guide',
    body: 'The MEAN stack combines MongoDB, Express, Angular and Node.js to build full stack JavaScript web applications end to end.',
  },
  {
    userId: 34,
    id: 34,
    title: 'Deploying Angular App Online',
    body: 'You can deploy Angular applications to platforms like Firebase, Netlify or Vercel with simple build and upload commands.',
  },
  {
    userId: 35,
    id: 35,
    title: 'Understanding Component Lifecycle Hooks',
    body: 'Angular lifecycle hooks like ngOnInit and ngOnDestroy let you run custom logic at specific stages of a component lifecycle.',
  },
  {
    userId: 36,
    id: 36,
    title: 'CSS Variables And Custom Properties',
    body: 'CSS custom properties allow you to store reusable values like colors and fonts that can be changed from one central place.',
  },
  {
    userId: 37,
    id: 37,
    title: 'Introduction To Web Accessibility',
    body: 'Web accessibility ensures your website can be used by people with disabilities through proper HTML semantics and ARIA roles.',
  },
  {
    userId: 38,
    id: 38,
    title: 'JavaScript Closures Made Simple',
    body: 'A closure is a function that remembers the variables from its outer scope even after the outer function has finished executing.',
  },
  {
    userId: 39,
    id: 39,
    title: 'Angular Pipes For Data Transformation',
    body: 'Angular pipes transform displayed data in templates using built-in pipes like date, currency, uppercase and custom pipe classes.',
  },
  {
    userId: 40,
    id: 40,
    title: 'Responsive Design With Media Queries',
    body: 'Media queries in CSS allow you to apply different styles based on screen size, making your website look good on all devices.',
  },
]